#!/usr/bin/ruby

require_relative 'rerun'
require_relative 'runscripts'
require_relative 'security'
require_relative 'functionality'
require_relative 'performance'
include RunScripts

#------------------------------------------------------------------------------
# Rerun
#------------------------------------------------------------------------------
# rerun

#------------------------------------------------------------------------------
# Security
#------------------------------------------------------------------------------
# cache_security
# execution_time_compare
# execution_time_compare_qsub
# security_debug
# paddr_test
# setpart_vs_private

#------------------------------------------------------------------------------
# Functionality
#------------------------------------------------------------------------------
# test_baseline
# test_secure
# test_only_mc
# test_only_rrbus
# test_only_waypart
# test_2tc
# test_turn_lengths

#------------------------------------------------------------------------------
# Performance
#----------------------------------------------------------------------------
# single 
# breakdown
# baseline
# ncore_2tc
# ncore_ntc
# ncore_ntc_no_part
# flush_overhead
# cache_sweep
# more_channels
# resource_alloc
# mem_alloc
# turn_length_sweep
relaxed_two_core
resource_alloc_relaxed
only_mc_relaxed
relaxed_2tc
