#!/usr/bin/ruby

require_relative 'rerun'
require_relative 'runscripts'
require_relative 'security'
require_relative 'functionality'
require_relative 'performance'
include RunScripts

#------------------------------------------------------------------------------
# Rerun
#------------------------------------------------------------------------------
# rerun

#------------------------------------------------------------------------------
# Security
#------------------------------------------------------------------------------
# cache_security
# execution_time_compare
# execution_time_compare_qsub
# security_debug
# paddr_test
# setpart_vs_private

#------------------------------------------------------------------------------
# Functionality
#------------------------------------------------------------------------------
# test_baseline
# test_secure
# test_only_mc
# test_only_rrbus
# test_only_waypart
# test_2tc

#------------------------------------------------------------------------------
# Performance
#----------------------------------------------------------------------------
# single 
# breakdown
# baseline
# ncore_2tc
# ncore_ntc
# ncore_ntc_no_part
flush_simple

# flush_overhead
# coordination
# parameter_tests
